Repository heig-PRO-b04/android-frontend, pull requests merged in 2020-05, with the labels that each got.

#56 Add a few corrections on the last merge
  app/src/main/java/ch/heigvd/pro/b04/android/Home/HomeViewModel.java
  app/src/main/java/ch/heigvd/pro/b04/android/Poll/PollViewModel.java
Labels: bug

#57 Add request to get Answers from Backend
  app/src/main/java/ch/heigvd/pro/b04/android/Datamodel/Answer.java
  app/src/main/java/ch/heigvd/pro/b04/android/Network/RockinAPI.java
  app/src/main/java/ch/heigvd/pro/b04/android/Question/Answer/Answer.java
  app/src/main/java/ch/heigvd/pro/b04/android/Question/Answer/AnswerAdapter.java
  app/src/main/java/ch/heigvd/pro/b04/android/Question/QuestionActivity.java
  app/src/main/java/ch/heigvd/pro/b04/android/Question/QuestionViewModel.java
Labels: enhancement

#72 Vote for answers and send said vote to backend
  app/src/main/java/ch/heigvd/pro/b04/android/Datamodel/Answer.java
  app/src/main/java/ch/heigvd/pro/b04/android/Datamodel/Question.java
  app/src/main/java/ch/heigvd/pro/b04/android/Network/RockinAPI.java
  app/src/main/java/ch/heigvd/pro/b04/android/Question/QuestionActivity.java
  app/src/main/java/ch/heigvd/pro/b04/android/Question/QuestionAdapter.java
  app/src/main/java/ch/heigvd/pro/b04/android/Question/QuestionViewModel.java
  app/src/main/res/values/colors.xml
Labels: enhancement, good first issue

#80 Use a LiveData to persist the authentication token
  app/src/main/java/ch/heigvd/pro/b04/android/Authentication/AuthenticationTokenLiveData.java
  app/src/main/java/ch/heigvd/pro/b04/android/Authentication/SessionToTokenWithPoll.java
  app/src/main/java/ch/heigvd/pro/b04/android/Authentication/TokenToTokenWithSession.java
  app/src/main/java/ch/heigvd/pro/b04/android/Datamodel/Answer.java
  app/src/main/java/ch/heigvd/pro/b04/android/Datamodel/Poll.java
  app/src/main/java/ch/heigvd/pro/b04/android/Datamodel/Question.java
  app/src/main/java/ch/heigvd/pro/b04/android/Home/Home.java
  app/src/main/java/ch/heigvd/pro/b04/android/Home/HomeViewModel.java
  app/src/main/java/ch/heigvd/pro/b04/android/Home/NavigateToPollViewModel.java
  app/src/main/java/ch/heigvd/pro/b04/android/Network/LiveDataCallAdapter.java
  app/src/main/java/ch/heigvd/pro/b04/android/Network/LiveDataCallAdapterFactory.java
  app/src/main/java/ch/heigvd/pro/b04/android/Network/RetrofitClient.java
  app/src/main/java/ch/heigvd/pro/b04/android/Network/RockinAPI.java
  app/src/main/java/ch/heigvd/pro/b04/android/Poll/PollActivity.java
  app/src/main/java/ch/heigvd/pro/b04/android/Poll/PollViewModel.java
  app/src/main/java/ch/heigvd/pro/b04/android/Poll/PollViewModelFactory.java
  app/src/main/java/ch/heigvd/pro/b04/android/Question/QuestionActivity.java
  app/src/main/java/ch/heigvd/pro/b04/android/Question/QuestionViewModel.java
  app/src/main/java/ch/heigvd/pro/b04/android/Utils/Exceptions/TokenNotSetException.java
  app/src/main/java/ch/heigvd/pro/b04/android/Utils/LocalDebug.java
  app/src/main/java/ch/heigvd/pro/b04/android/Utils/Persistent.java
  app/src/main/java/ch/heigvd/pro/b04/android/Utils/PollingLiveData.java
  app/src/main/java/ch/heigvd/pro/b04/android/Utils/Unit.java
Labels: enhancement

#88 Allow the button color to reflect the last given vote at all times
  app/src/main/java/ch/heigvd/pro/b04/android/Question/QuestionAdapter.java
Labels: bug

#85 Show the description of an answer
  app/src/main/java/ch/heigvd/pro/b04/android/Question/QuestionAdapter.java
Labels: enhancement, good first issue, ui

#87 Allow answer modification
  app/src/main/java/ch/heigvd/pro/b04/android/Question/QuestionViewModel.java
Labels: bug, enhancement

#98 Make emoji buttons square
  app/src/main/java/ch/heigvd/pro/b04/android/Home/EmojiGridAdapter.java
  app/src/main/java/ch/heigvd/pro/b04/android/Home/Home.java
  app/src/main/java/ch/heigvd/pro/b04/android/Utils/SquareCardView.java
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/home_grid_item.xml
  app/src/main/res/values/ids.xml
Labels: enhancement, ui

#99 Overlap the two login info buttons
  app/src/main/java/ch/heigvd/pro/b04/android/Home/Home.java
  app/src/main/java/ch/heigvd/pro/b04/android/Home/HomeViewModel.java
  app/src/main/res/drawable/ic_qr_scanner_error.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/home_code_card_view.xml
  app/src/main/res/values/ids.xml
Labels: enhancement, question, ui

#101 Add a button to disconnect us from the current poll
  app/src/main/java/ch/heigvd/pro/b04/android/Poll/PollActivity.java
  app/src/main/res/drawable/ic_exit_app.xml
  app/src/main/res/layout/activity_poll.xml
  app/src/main/res/values/ids.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, ui

#103 Add an ApiResponse type that wraps API errors
  app/src/main/java/ch/heigvd/pro/b04/android/Authentication/SessionToTokenWithPoll.java
  app/src/main/java/ch/heigvd/pro/b04/android/Authentication/TokenToTokenWithSession.java
  app/src/main/java/ch/heigvd/pro/b04/android/Network/ApiResponse.java
  app/src/main/java/ch/heigvd/pro/b04/android/Network/LiveDataCallAdapter.java
  app/src/main/java/ch/heigvd/pro/b04/android/Network/LiveDataCallAdapterFactory.java
  app/src/main/java/ch/heigvd/pro/b04/android/Network/LiveDataUtils.java
  app/src/main/java/ch/heigvd/pro/b04/android/Network/RockinAPI.java
  app/src/main/java/ch/heigvd/pro/b04/android/Question/QuestionViewModel.java
Labels: enhancement

#108 Fix #107
  app/src/main/java/ch/heigvd/pro/b04/android/Home/Home.java
Labels: enhancement, ui

#109 Disconnect when token is invalid
  app/src/main/java/ch/heigvd/pro/b04/android/Network/RockinAPI.java
  app/src/main/java/ch/heigvd/pro/b04/android/Poll/PollActivity.java
  app/src/main/java/ch/heigvd/pro/b04/android/Question/QuestionActivity.java
  app/src/main/java/ch/heigvd/pro/b04/android/Question/QuestionViewModel.java
Labels: enhancement

#112 Disconnect poll
  app/src/main/java/ch/heigvd/pro/b04/android/Network/RockinAPI.java
  app/src/main/java/ch/heigvd/pro/b04/android/Poll/PollActivity.java
  app/src/main/java/ch/heigvd/pro/b04/android/Poll/PollViewModel.java
  app/src/main/java/ch/heigvd/pro/b04/android/Question/QuestionActivity.java
  app/src/main/java/ch/heigvd/pro/b04/android/Question/QuestionUtils.java
  app/src/main/java/ch/heigvd/pro/b04/android/Question/QuestionViewModel.java
Labels: enhancement

#117 Make answers update
  app/src/main/java/ch/heigvd/pro/b04/android/question/QuestionViewModel.kt
Labels: bug

#120 Order answers by answerID
  app/src/main/java/ch/heigvd/pro/b04/android/question/QuestionViewModel.kt
Labels: enhancement

#122 Fix votes alert
  app/src/main/java/ch/heigvd/pro/b04/android/question/QuestionActivity.kt
  app/src/main/java/ch/heigvd/pro/b04/android/question/QuestionViewModel.kt
  app/src/main/res/values/strings.xml
Labels: bug, enhancement, ui

#126 Add a PollState to handle the question ViewModel state
  app/src/main/java/ch/heigvd/pro/b04/android/question/PollState.kt
  app/src/main/java/ch/heigvd/pro/b04/android/question/QuestionActivity.kt
  app/src/main/java/ch/heigvd/pro/b04/android/question/QuestionAdapter.kt
  app/src/main/java/ch/heigvd/pro/b04/android/question/QuestionUtils.java
  app/src/main/java/ch/heigvd/pro/b04/android/question/QuestionViewModel.kt
  app/src/main/res/layout/activity_question.xml
Labels: enhancement, good first issue

#128 Fix wrong message bug
  app/src/main/java/ch/heigvd/pro/b04/android/question/PollState.kt
  app/src/main/java/ch/heigvd/pro/b04/android/question/QuestionActivity.kt
Labels: bug, ui

#133 Documentation
  app/src/main/java/ch/heigvd/pro/b04/android/authentication/TokenToTokenWithSession.java
  app/src/main/java/ch/heigvd/pro/b04/android/datamodel/Answer.java
  app/src/main/java/ch/heigvd/pro/b04/android/datamodel/Question.java
  app/src/main/java/ch/heigvd/pro/b04/android/datamodel/Session.java
  app/src/main/java/ch/heigvd/pro/b04/android/datamodel/Token.java
  app/src/main/java/ch/heigvd/pro/b04/android/home/Emoji.java
  app/src/main/java/ch/heigvd/pro/b04/android/home/EmojiCodeAdapter.java
  app/src/main/java/ch/heigvd/pro/b04/android/home/EmojiGridAdapter.java
  app/src/main/java/ch/heigvd/pro/b04/android/home/HomeActivity.java
  app/src/main/java/ch/heigvd/pro/b04/android/home/HomeViewModel.java
  app/src/main/java/ch/heigvd/pro/b04/android/home/NavigateToPollViewModel.java
  app/src/main/java/ch/heigvd/pro/b04/android/home/State.java
  app/src/main/java/ch/heigvd/pro/b04/android/network/LiveDataCallAdapter.java
  app/src/main/java/ch/heigvd/pro/b04/android/network/NetworkError.kt
  app/src/main/java/ch/heigvd/pro/b04/android/network/RequestsViewModel.kt
  app/src/main/java/ch/heigvd/pro/b04/android/network/RockinAPI.kt
  app/src/main/java/ch/heigvd/pro/b04/android/poll/PollActivity.kt
  app/src/main/java/ch/heigvd/pro/b04/android/poll/PollAdapter.kt
  app/src/main/java/ch/heigvd/pro/b04/android/poll/PollViewModel.kt
  app/src/main/java/ch/heigvd/pro/b04/android/question/PollState.kt
  app/src/main/java/ch/heigvd/pro/b04/android/question/QuestionActivity.kt
  app/src/main/java/ch/heigvd/pro/b04/android/question/QuestionAdapter.kt
  app/src/main/java/ch/heigvd/pro/b04/android/utils/LocalDebug.java
  app/src/main/res/layout/question_activity.xml
  app/src/main/res/values/strings.xml
Labels: documentation
